version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

  clean:
    steps:
      - run:
          name: Clean Database
          command: "curl https://svelte-smart-weather.herokuapp.com/logs/clean"

workflows:
  deploy:
    jobs:
      - build