version: 2.1
orbs:
  heroku: circleci/heroku@1.2.4
jobs:
  build:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  deploy:
    jobs:
      - build
  node-tests:
    jobs:
      - node/test